### ISSUE TITLE
How I can do Corner radius to tabbed page

### ISSUE THREAD

**Issue by KevinAnass** [saeedafshari/RedCorners.Forms#2]
i need to  do this task with xamarin forms 
![temp1](https://user-images.githubusercontent.com/59505755/101165931-c0c26a80-3637-11eb-8d26-df926d249fab.PNG)

**Comment by samafshari** [comment]
You can put a tabbed page with invisible tab bar on the back, and a tab bar with a frame as its background on the front. Bind SelectedIndex properties together and you'll get what you want.
