### ISSUE TITLE
Also not Issue: is it possible to open side menu without blocking gestures on main view?

### ISSUE THREAD

**Issue by madmapper** [saeedafshari/RedCorners.Forms#4]
Using your awesome side menu to implement a side drawer with some map controls.  Is it possible to have the menu open without blocking gesture events to the view behind?  Ideally we want the user to be able to continue to zoom/pan the map while the menu is open.  

Thanks!

**Comment by madmapper** [comment]
Disregard - was able to accommodate this by using a stack layout

**Comment by samafshari** [comment]
You can disable SideBar open swipe gestures. See SideBar.IsSwipeEnabled (SideBar.xaml.cs)
